### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by LunevNF** [JakeSteam/Vidsta#14]
Hello. Can't create object programmatically. What's wrong?

                    final VidstaPlayer videoView = new VidstaPlayer(thisActivityContext);
                    params = new LinearLayout.LayoutParams(
                            ViewGroup.LayoutParams.MATCH_PARENT,
                            HelpFuncs.getPixelsFromDP(thisActivityContext, 150)
                    );
                    params.leftMargin = HelpFuncs.getPixelsFromDP(thisActivityContext, 4);
                    params.rightMargin = HelpFuncs.getPixelsFromDP(thisActivityContext, 4);
                    params.topMargin = HelpFuncs.getPixelsFromDP(thisActivityContext, 4);
                    params.bottomMargin = HelpFuncs.getPixelsFromDP(thisActivityContext, 4);
                    params.gravity = Gravity.CENTER;
                    videoView.setLayoutParams(
                            params
                    );
                    rootObjectsLL.addView(videoView);

                    videoView.setTextColor(Color.WHITE);
                    videoView.setVideoSource(Uri.parse(element.getValue()));
                    videoView.setFullScreenButtonVisible(true);`

Error:

> 06-24 20:18:56.660 1407-1407/ru.parjok.app1 E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NullPointerException
        at uk.co.jakelee.vidsta.VidstaPlayer.setTextColor(VidstaPlayer.java:718)
        at ru.parjok.app1.activities.ContentElementActivity.appendElementsOnForm(ContentElementActivity.java:214)
        at ru.parjok.app1.activities.ContentElementActivity.access$200(ContentElementActivity.java:53)
        at ru.parjok.app1.activities.ContentElementActivity$4$1.doInUIThread(ContentElementActivity.java:253)
        at com.arasthel.asyncjob.AsyncJob$1.run(AsyncJob.java:46)
        at android.os.Handler.handleCallback(Handler.java:730)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:5419)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by LunevNF** [comment]
Exception on line 

> videoView.setTextColor(Color.WHITE);

**Comment by LunevNF** [comment]
OK, Just use in Another Library.
